lib: [
  "_build/install/default/lib/ocamlfdo/META"
  "_build/install/default/lib/ocamlfdo/dune-package"
  "_build/install/default/lib/ocamlfdo/opam"
]
bin: [
  "_build/install/default/bin/ocamlfdo"
  "_build/install/default/bin/ocamlfdo.exe"
]
etc: [
  "_build/install/default/etc/ocamlfdo/linker-script"
]
doc: [
  "_build/install/default/doc/ocamlfdo/LICENSE"
  "_build/install/default/doc/ocamlfdo/README.md"
]
